# Generated by Django 5.2.5 on 2025-09-01 17:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=120)),
                ('contenido', models.TextField()),
                ('creada', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-creada'],
            },
        ),
    ]
